### ISSUE TITLE
Use official pypa/gh-action-pypi-publish worflow to publish package

### ISSUE THREAD

**Issue by jbutcher5** [asger-weirsoee/sway-smart-workspaces#8]
Currently we are just uploading the package with a shell command, it would be best for future maintenance to use the official https://github.com/pypa/gh-action-pypi-publish.
https://github.com/asger-weirsoee/sway-smart-workspaces/blob/85670628cb467e8e79451d48e9a361dc974aa7f5/.github/workflows/python-publish.yml#L25-L31
If we were to remove this code and replace it with pypa/gh-action-pypi-publish we would no longer need to install `twine`. This shortens the upload time as twine will not need to be installed.

Example usage of pypa/gh-action-pypi-publish would look like 
```yaml
- name: Publish a Python distribution to PyPI
  uses: pypa/gh-action-pypi-publish@release/v1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
```
